######################################
## Site settings                    ##
######################################
title:       Junior Theme
email:       jonathon.bel.melbourne@gmail.com
author:      Jonathon Belotti
description: "A striking black-white Jekyll theme."
baseurl:     ""
url:         "https://juniortheme.live/"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

######################################
## Optional features                ##
######################################
animated:             false
show_related_posts:   false
show_post_footers:    True
show_social_icons:    True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

######################################
## Optional site sections           ##
######################################
show_talks_section:     true
show_workshops_section: true

######################################
## Disqus post comments             ##
## (leave blank to disable Disqus)  ##
######################################
disqus_shortname: 'juniortheme-live'

##########################################################################
## Facebook Comments plugin                                             ##
## (leave blank to disable Facebook Comments, otherwise set it to true) ##
##########################################################################
facebook_comments:
facebook_appid:
facebook_comments_number: 10

###################################
## Social icons                  ##
###################################
github_username: thundergolfer
bitbucket_username:
stackoverflow_id:
twitter_username: jonobelotti_io
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: jonathonbelotti
angellist_username:
medium_id: thundergolfer
youtube_channel_id: UCSP7fMKwmaXaZhViAV2Vgvg
bitcoin_url:
paypal_url:
flattr_button:

###################################
## Post sharing icons            ##
###################################
show_sharing_icons: True
# Change to 'true' to enable individual icons
share_facebook: True
share_twitter: True
share_googleplus: True
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: True
share_stumbleupon: false
share_hackernews: True

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

############################################
## Build settings                         ##
############################################
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    pretty
paginate:     4
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

#################################################
## Collections (for 'Design' section of site)  ##
#################################################
collections:
  portfolio:
    output: true
